// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package org.kaaproject.avro.ui.gwt.client;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
interface AvroUiTheme extends CssResource {
  
  String actionPopup();
  
  String active();
  
  @ClassName("b-app-content")
  String bAppContent();
  
  @ClassName("Bottom")
  String bottom();
  
  String bottomCenter();
  
  String bottomLeft();
  
  String bottomRight();
  
  String breadcrumb();
  
  String busyGlass();
  
  String busyPopup();
  
  String buttonSmall();
  
  String buttonsPanel();
  
  @ClassName("Caption")
  String caption();
  
  String cellButton();
  
  String cellButtonSmall();
  
  String closeAction();
  
  String content();
  
  String dialogBottomCenter();
  
  String dialogBottomLeft();
  
  String dialogBottomRight();
  
  String dialogContent();
  
  String dialogMiddleLeft();
  
  String dialogMiddleRight();
  
  String dialogTopLeft();
  
  String dialogTopRight();
  
  String divider();
  
  String error();
  
  String fieldNotes();
  
  String fieldSet();
  
  String fieldsetInvisible();
  
  String fieldsetVisible();
  
  String fieldWidget();
  
  String formPopup();
  
  @ClassName("gwt-DialogBox")
  String gwtDialogBox();
  
  @ClassName("gwt-HTML")
  String gwtHTML();
  
  @ClassName("gwt-Label")
  String gwtLabel();
  
  String hint();
  
  @ClassName("icon-error")
  String iconError();
  
  @ClassName("icon-hint")
  String iconHint();
  
  @ClassName("icon-info")
  String iconInfo();
  
  @ClassName("icon-success")
  String iconSuccess();
  
  @ClassName("icon-warning")
  String iconWarning();
  
  String info();
  
  String invalidField();
  
  String legend();
  
  String legendCheckBox();
  
  String legendImage();
  
  String legendLabel();
  
  String legendNotes();
  
  String legendPanel();
  
  String linkCell();
  
  String middleRight();
  
  String navAction();
  
  String noPrompt();
  
  String padded();
  
  String prompt();
  
  String requiredField();
  
  String resizeHandle();
  
  String resizePanel();
  
  String secondaryLabel();
  
  String success();
  
  String topCenter();
  
  String topCenterInner();
  
  String topLeft();
  
  String topRight();
  
  @ClassName("ui-icon")
  String uiIcon();
  
  @ClassName("ui-icon-error")
  String uiIconError();
  
  @ClassName("ui-icon-hint")
  String uiIconHint();
  
  @ClassName("ui-icon-info")
  String uiIconInfo();
  
  @ClassName("ui-icon-success")
  String uiIconSuccess();
  
  @ClassName("ui-icon-warning")
  String uiIconWarning();
  
  @ClassName("ui-message")
  String uiMessage();
  
  String warning();
  
  String zoomAction();
  
  String zoomActionPanel();
}

