// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package org.kaaproject.avro.ui.sandbox.client;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
interface AvroUiSandboxTheme extends CssResource {
  
  @ClassName("b-app-content-details-table")
  String bAppContentDetailsTable();
  
  @ClassName("b-app-content-title")
  String bAppContentTitle();
  
  @ClassName("b-app-header-title")
  String bAppHeaderTitle();
  
  @ClassName("gwt-HTML")
  String gwtHTML();
  
  @ClassName("gwt-Label")
  String gwtLabel();
}

